
@Api_HostAddress = http://localhost:5007

POST {{Api_HostAddress}}/api/auth
Content-Type: application/json

{
    "email": "email",
    "password": "password"
}

###
GET {{Api_HostAddress}}/api/users/@me
Accept: application/json

###
